services:
  db:
    image: postgres:14
    container_name: salesforge-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - salesforge-network

volumes:
  pgdata:

networks:
  salesforge-network:
